disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - shorthand_operator
  - file_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Library
